### ISSUE TITLE
Why is the function async?

### ISSUE THREAD

**Issue by nahtnam** [ovhemert/pino-datadog#22]
Hey,

Just wondering why this function is async? https://github.com/ovhemert/pino-datadog/blob/4875979f488aafdb5cc661a8560fe08cf3b666d7/src/index.js#L7

It makes it so that I can't use this in the top level of my file.

Thanks,
Manthan M

**Comment by ovhemert** [comment]
This is actually something that was left there from a previous version. It's not strictly needed, but there for backwards compatibility. 

If you'd like to use the function in your own application at the top level, you could call the function as if it was a Promise, like `ceateWriteStream().then(...)`.

I hope this answers your question.

**Comment by devilleweppenaar** [comment]
I was about to log the same question but then saw this one. :smile:

We're busy with a migration from winston to pino, and luckily we have a shared logging package that we use in our 30+ microservices. But with this function remaining async, it makes it quite difficult to do a drop-in replacement without updating all of the dependent projects' logger initialization code.

For our purposes to work, we'd like to be able to do the following:
```js
const datadog = require('pino-datadog')
const pinoms = require('pino-multi-stream')

function Logger () {
  const writeStream = datadog.createWriteStream()

  const logger = pinoms({ streams: [writeStream] })

  // custom logger logic

  return logger
}

const logger = Logger()

module.exports = { logger, Logger }
```

With this file living in our shared logger package, and `logger` being imported in any dependent applications.

Would you consider releasing a version 2.0.0 with this change, given that it breaks backward compatibility? I'm also happy to create a PR for it if that would help.

**Comment by nahtnam** [comment]
^ My use case was similar to this one

EDIT: I'm using a package for a different reason so this is no longer needed from me though

**Comment by ovhemert** [comment]
Seems like this issue is still coming back.

I've added a new function `createWriteStreamSync` to support this, and so it does not break compatibility. I'll soon bump version and release this as a patch.
