### ISSUE TITLE
Strange behavious with option "size"

### ISSUE THREAD

**Issue by MarkusVo** [ovhemert/pino-datadog#33]
Stream with option "size": 10 seems to behave really weird thus it won't send my Logs to the DataDog API but when I remove the options everything works fine.

Is there something broken with the implementation?

Because taken from the docs:

```
size
Type: String (optional)

The number of log messages to send as a single batch (defaults to 1).
```
What I would have expected was that if I want to send a single Log to the DataDog API that there shouldnt be a problem.

But as long as I kept that option no Log got through.

**Comment by ovhemert** [comment]
How many logs do you send? When you have the batch size set to 10, you should at least send 10 logs for then to pass through as a batch, otherwise they will be kept in memory until there are 10.

Can you add an example of your code?

**Comment by MarkusVo** [comment]
Oh okay! Seems that it was my bad then! Was just not expecting that providing a batch size kind of expects me to send batches of the given size! :) Anyways guess this solved my problem thanks for your response this Issue can be close! :)
