### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by haroldadmin** [ovhemert/pino-datadog#62]
## 🚀 Feature Proposal

Please add TypeScript types to this project. It is written in JavaScript and does not bundle type definitions. If that's not possible, please consider adding types to `@types/pino-datadog`.

## Motivation

I'm working on a project in TypeScript and would like to use this library to stream logs to Datadog.

## Example

While I could not find other pino loggers for Datadog, there are a few examples available for Winston that might serve as a starting point:
- `datadog-winston`: https://www.npmjs.com/package/datadog-winston

**Comment by czystyl** [comment]
cc @haroldadmin the types are already merged so soon you'll be able to use types in your project! 

reference: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55649
